### ISSUE TITLE
v2.0 is broken: src/PlotConfigurationDialog.cpp file is missing

### ISSUE THREAD

**Issue by dominig** [seandepagnier/sweepplot_pi#10]
the last commit from May 18th, <d756aa41a0cc54b204607c4a84fed042f0cd9eb4> introduces a new file 
in CMakeList.txt 
src/PlotConfigurationDialog.cpp
That file is no where in the git repo and so compilation fails.
**In short v 2.0 is broken.**

-------------------- log -----------
CMake Error at CMakeLists.txt:45 (ADD_LIBRARY):
  Cannot find source file:
    src/PlotConfigurationDialog.cpp

**Comment by rgleason** [comment]
Dominig this is fixed.
https://github.com/seandepagnier/sweepplot_pi/commit/1646c92910278a602f80b54b23e60d84072bb440
 Can we close it now?
