### ISSUE TITLE
Openpn Failure, if no data available when Sweepplot opened.

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/sweepplot_pi#13]
If there is no data available when Sweepplot Icon is clicked, opencpn seems to fail.
I think this is  a bug.

**Comment by seandepagnier** [comment]
fail how?

**Comment by rgleason** [comment]
Seems to have trouble initializing sometimes.
From log file.
```
9:49:57 AM: Found LanguageInfo for: English
9:50:15 AM: PlugInManager: Initializing PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
09:50:41: 
```

Later```

9:50:53 AM: PlugInManager: Loading PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
9:50:53 AM:   C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
              API Version detected: 110
              PlugIn Version detected: 200
```

10:07:02 AM: Loading catalog for:  opencpn-sweepplot_pi
..

```
10:07:06 AM: PlugInManager: Deactivating PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
..
10:07:14 AM: Loading catalog for:  opencpn-sweepplot_pi
...
10:07:14 AM: Found LanguageInfo for: English
10:07:18 AM: PlugInManager: Initializing PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
10:07:21 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:07:22 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:07:41: 

```

Then Opencpn fails.

Later

```
10:28:18 AM: Found LanguageInfo for: English
10:28:26 AM: PlugInManager: Initializing PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
10:28:35 AM: PlugInManager: Deactivating PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
10:29:06: 
```
Opencpn fails.

---Does it have something to do with hitting  Enable ,  not hitting Apply button,  then hitting Disable?.

This last sequence also ended in a failure.

```
10:29:18 AM: PlugInManager: Loading PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
10:29:18 AM:   C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
              API Version detected: 110
              PlugIn Version detected: 200
10:29:31 AM: PlugInManager: Initializing PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
10:29:34 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:29:36 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:29:49 AM: PlugInManager searching for PlugIns in location C:\Program Files (x86)\OpenCPN 4.8.2\plugins
10:29:49 AM: Loading catalog for:  opencpn-sweepplot_pi
10:29:49 AM: Loading catalog for opencpn core.
10:29:49 AM: Getting DefaultSystemLocale...
10:29:49 AM: Found LanguageInfo for: English
10:29:52 AM: PlugInManager: Deactivating PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
10:29:54 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:29:56 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:30:02 AM: PlugInManager searching for PlugIns in location C:\Program Files (x86)\OpenCPN 4.8.2\plugins
10:30:02 AM: Loading catalog for:  opencpn-sweepplot_pi
10:30:02 AM: Loading catalog for opencpn core.
10:30:02 AM: Getting DefaultSystemLocale...
10:30:02 AM: Found LanguageInfo for: English
10:30:05 AM: PlugInManager: Initializing PlugIn: C:\Program Files (x86)\OpenCPN 4.8.2\plugins\sweepplot_pi.dll
10:30:10 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:30:12 AM: Metrics:  m_display_size_mm: 254     wxDisplaySize:  2160:1440   
10:30:12 AM: LOGBOOK:  2018-03-05 15:30:12 UTC  DR Lat   52.46340 Lon    5.07370


I've tried to figure out if it is related to some action or sequence, but if opencpn fails, and I load Opencpn again, the plugin usually works.

![screenshot 93](https://user-images.githubusercontent.com/2363959/36984644-5fb98e7c-2063-11e8-8b9a-1eb69cb4a58e.png)
![screenshot 92](https://user-images.githubusercontent.com/2363959/36984657-66ba1214-2063-11e8-9544-ccf54507c859.png)
![screenshot 91](https://user-images.githubusercontent.com/2363959/36984668-6ea053f8-2063-11e8-9953-3d7a1a9dd216.png)
![screenshot 90](https://user-images.githubusercontent.com/2363959/36984692-77df7444-2063-11e8-9b64-07617578f732.png)

The issue is definitely repeatable, and it is related to Enabling and Disabling the plugin.
I have tried various sequences like Enable or Disable and then closing Opencpn and opening, etc. to see what happens. Haven't been able to determing a particular combo which causes it.  Sorry.

**Comment by rgleason** [comment]
Now works very nicely. Fixed. No Crash. Thank you, Sean. An excellent plugin for sailors.

Windows: https://github.com/rgleason/sweepplot_pi/releases
