### ISSUE TITLE
Changes in Transparency value do not show until the PI Toolbar button is toggled.

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/sweepplot_pi#16]
To get changes in transparency to show, you have to toggle the Sweepplot Toolbar Button.

Should this be a note in the manual? or can it be improved?

--Made a note in the manual too.

**Comment by rgleason** [comment]
Added to the manual the way the on-the-fly Configuration Menu is accessed and what it does.

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:sailing_tools:sweep_plot#configuration

**Comment by rgleason** [comment]
This still operates this way, I've made a note in the Wiki.  Closing

**Comment by seandepagnier** [comment]
This isn't going to changem, sorry.

**Comment by rgleason** [comment]
No problem. Thanks for letting me know. I've got it covered in the wiki.
