### ISSUE TITLE
Cannot Compile missing plots_pi.cpp

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/sweepplot_pi#17]
-- Found OpenGL: opengl32
-- Found OpenGL...
--     Lib: glu32opengl32
--     Include:
-- Found Gettext: C:/Program Files (x86)/Poedit/GettextTools/bin/msgmerge.exe
-- Install Prefix: C:/Program Files (x86)/plots_pi
-- FILE: plots_pi-2.2-win32.exe
-- Configuring done
CMake Error at CMakeLists.txt:45 (ADD_LIBRARY):
  Cannot find source file:

    src/plots_pi.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: plots_pi
-- Generating done
-- Build files have been written to: C:/Users/Rick/Documents/GitHub/plots_pi/build

**Comment by rgleason** [comment]
Sean during the recent change from sweepplot_pi to plots_pi
a number of files were simply removed similar to plot_pi.cpp
https://github.com/seandepagnier/plots_pi/commit/d052bfce73739d725fd9760f14ff8002f9716cbf#diff-66dd905bbf9398c1769cdb9a679b5934

I count about seven or eight files were just totally removed.
See 
https://github.com/seandepagnier/plots_pi/commit/d052bfce73739d725fd9760f14ff8002f9716cbf#diff-66dd905bbf9398c1769cdb9a679b5934

I'd go back to previous commit before you renamed and start over.

**Comment by seandepagnier** [comment]
I probably forgot to add the renamed  files, thanks for informing me.

**Comment by rgleason** [comment]
Sean, do you want the Wiki to be renamed to "Plots" as well?
(... once you update your repos and I can compile it again. )

**Comment by rgleason** [comment]
Sean, I git fetched and there is still something missing.


Build FAILED.

"C:\Users\Rick\Documents\GitHub\plots_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(208): error C2065: 'wxJSONWriter' : unde
clared identifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(208): error C2146: syntax error : missin
g ';' before identifier 'w' [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(208): error C2065: 'w' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(210): error C2065: 'wxJSONValue' : undec
lared identifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(210): error C2146: syntax error : missin
g ';' before identifier 'v' [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(210): error C2065: 'v' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(211): error C2065: 'w' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(211): error C2228: left of '.Write' must
 have class/struct/union [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(211): error C2065: 'v' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(362): error C2065: 'wxJSONReader' : unde
clared identifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(362): error C2146: syntax error : missin
g ';' before identifier 'r' [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(362): error C2065: 'r' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(363): error C2065: 'wxJSONValue' : undec
lared identifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(363): error C2146: syntax error : missin
g ';' before identifier 'v' [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(363): error C2065: 'v' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(366): error C2065: 'r' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(366): error C2228: left of '.Parse' must
 have class/struct/union [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(366): error C2065: 'v' : undeclared iden
tifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(367): error C2065: 'root' : undeclared i
dentifier [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(367): error C2228: left of '.AsString' m
ust have class/struct/union [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\plots_pi.cpp(367): error C2228: left of '.ToDouble' m
ust have class/struct/union [C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj]

    0 Warning(s)
    21 Error(s)

**Comment by rgleason** [comment]
Sean just fetched your recent changes for json, and tried to compile.
Got these errors now.


Build FAILED.

"C:\Users\Rick\Documents\GitHub\plots_pi\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Rick\Documents\GitHub\plots_pi\build\plots_pi.vcxproj" (default target) (3) ->
(ClCompile target) ->
  C:\Users\Rick\Documents\GitHub\plots_pi\src\wxJSON\jsonreader.cpp(15): fatal error C1083: Cannot
open include file: 'wx/jsonreader.h': No such file or directory [C:\Users\Rick\Documents\GitHub\plo
ts_pi\build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\wxJSON\jsonval.cpp(27): fatal error C1083: Cannot ope
n include file: 'wx/jsonval.h': No such file or directory [C:\Users\Rick\Documents\GitHub\plots_pi\
build\plots_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\plots_pi\src\wxJSON\jsonwriter.cpp(16): fatal error C1083: Cannot
open include file: 'wx/jsonwriter.h': No such file or directory [C:\Users\Rick\Documents\GitHub\plo
ts_pi\build\plots_pi.vcxproj]

    0 Warning(s)
    3 Error(s)

**Comment by rgleason** [comment]
Sean, Thanks!  That fixed it.  Closing.
