### ISSUE TITLE
Plots not working in OpenCpn on raspberry pi

### ISSUE THREAD

**Issue by cbwarren** [seandepagnier/sweepplot_pi#25]
When I install this plugin on OpenPlotter/opencpn on my R-Pi, it loads, but when I enable it, the preference window is greyed and won't open and the plugin doesn't appear back in openCPN. I've done the usual cycle of restarting OPenCPN and rebooting, then restarting, but nothing works. Running 5.2.4 opencpn and the Plots version is 2.2.4.. And my Pi has been updated also.

can't see anyone reporting this issue in the Cruisers forum/opencpn portion.

**Comment by rgleason** [comment]
I think this can be closed now. It should work.  Sean or  cbwarren can close. I can't

**Comment by rgleason** [comment]
can be closed by @seandepagnier

**Comment by rgleason** [comment]
@cbwarren   Please close this, it is very old and the newer version is working.

**Comment by rgleason** [comment]
Thanks Sean. Hope you arent getting the winds and rain we are right now!
