### ISSUE TITLE
Feature Request: Develop SweepPlot further as the History plugin for Dashboard

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/sweepplot_pi#8]
http://willkamp.com/opencpn/flyspray/index.php?do=details&task_id=1653&project=5&order=votes&sort=desc

Add data types:
Wind Speed
Wind Direction
Cross Track

Adding other nmea data types like
rudder angle
relative humidity
specific humidity
presssure
air temperature
wind speed
Wind direction

Adopt the plugin for HISTORY Data in Dashboard or Perhaps it simply stays as a separate plugin that is augmented to show all Historic Data

Improved to export saved nmea files.

**Comment by seandepagnier** [comment]
I would implement a lot more data types in the sweep plot if only I had that data available.

I will keep separate from the dashboard.

**Comment by rgleason** [comment]
We really need to get you some instruments somehow!

**Comment by rgleason** [comment]
Sean,
I am going to close this now. OK?
